### ISSUE TITLE
How to add a new language?

### ISSUE THREAD

**Issue by s-a** [wooorm/retext-simplify#3]
Hi,
it might be cool to add a "how to add a new language" to the retext plugins. Does a decorated "awesome retext" list anywhere :smiley: ?

**Comment by wooorm** [comment]
Good idea! For now, just the [README of retext](https://github.com/wooorm/retext#list-of-plugins) contains information.

For other languages, I suggest cloning this repo, trashing `.git`, replacing all instances of `simplify` with another name (possibly suffixed by a language code? e.g., `retext-simplify-nl` for dutch), and changing the [data](https://github.com/wooorm/retext-simplify/blob/master/data/index.json)!

**Comment by s-a** [comment]
I would suggest to a add a ```setLanguage()``` methode and rename ```/data/index.json``` to ```/data/EN-gb.json``` and use this as fallback if the given language does not exist. If we clone plugin repos we cannot benefit from improvements authors make in their codes.

**Comment by s-a** [comment]
Maybe this issue might be more addressed to the https://github.com/wooorm/retext constructor where the plugins could ask for the current language?

**Comment by wooorm** [comment]
I’d rather not build that into retext, it’s not as easy as just specifying languages because sentences and paragraphs can contain multiple languages. It’s not very easy.

And, another problem is the size of packages: my preference is to keep the size low. retext-simplify is 18KB, of which around 17KB is the database. If I were to add other languages, those would significantly increase the size for the English language, and for the other languages themselves.

An alternative would be to publish different packages from one (this) repository. That could also work.

But, for now this is all theoretical; are you in fact considering creating patterns for other languages?

**Comment by s-a** [comment]
> I’d rather not build that into retext, it’s not as easy as just specifying languages because sentences and paragraphs can contain multiple languages. It’s not very easy.

Yes this is true. 

> And, another problem is the size of packages: my preference is to keep the size low. retext-simplify is 18KB, of which around 17KB is the database. If I were to add other languages, those would significantly increase the size for the English language, and for the other languages themselves.

Well for example Moment.js ships different locales and let the developer decide what they want to deploy in their packages.  https://github.com/moment/moment/tree/develop/locale 

> are you in fact considering creating patterns for other languages?

Yes I think about to write some text author helping tools for german language. Watching retext for some time and the last missing element was a spelling checker :smile:

**Comment by wooorm** [comment]
> Well for example Moment.js ships different [...]

Difference being that moment users (often) need multiple locales at the same time, plus that the localisation is quite small.

> Yes I think about to write some text author helping tools for german language [...]

Cool! :+1: Also check out [`parse-dutch`](https://github.com/wooorm/parse-dutch), you’ll probably want to create something like that, for German, too!

For now, I’d say we wait until there are actual translations, before making a decision.
